name: Setup Windows 11 Pro Gaming RDP

on:
  workflow_dispatch:
    inputs:
      rdp_password:
        description: 'RDP Password'
        required: true
        type: string

jobs:
  setup_rdp:
    name: Setup Gaming RDP
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure RDP
      run: |
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # Set RDP password from input
        $password = ConvertTo-SecureString "${{ github.event.inputs.rdp_password }}" -AsPlainText -Force
        $user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name.Split('\')[1]
        Set-LocalUser -Name $user -Password $password
        
        # Configure RDP settings for better performance
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "fEnableWinStation" -Value 1
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "fInheritAutoLogon" -Value 1
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "fInheritReconnectSame" -Value 1
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "fInheritInitialProgram" -Value 1
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "fInheritColorDepth" -Value 1
        
        # Set color depth to 32-bit
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "ColorDepth" -Value 4
        
        # Configure for gaming performance
        Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -name "fDisableCdm" -Value 0
        Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -name "MaxMonitors" -Value 4
        Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -name "MaxXResolution" -Value 7680
        Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -name "MaxYResolution" -Value 4320
        Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -name "bEnumerateHWBeforeSW" -Value 1
        
        # Restart RDP service
        Restart-Service TermService -Force

    - name: Install Gaming Components
      run: |
        # Install DirectX
        choco install directx -y
        
        # Install Visual C++ Redistributables
        choco install vcredist-all -y
        
        # Install .NET Framework
        choco install dotnetfx -y
        
        # Install gaming optimizations
        choco install gamebar -y
        choco install geforce-experience -y # If using NVIDIA
        choco install radeon-software -y # If using AMD
        
        # Disable Windows Game Bar
        reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR" /v AppCaptureEnabled /t REG_DWORD /d 0 /f
        reg add "HKCU\System\GameConfigStore" /v GameDVR_Enabled /t REG_DWORD /d 0 /f

    - name: Configure Network
      run: |
        # Set network throttling to 30Mbps (simulated)
        netsh int tcp set global autotuninglevel=restricted
        netsh interface tcp set global rss=enabled
        
        # Configure QoS for RDP
        New-NetQosPolicy -Name "RDP" -AppPathNameMatchCondition "svchost.exe" -IPProtocolMatchCondition Both -IPSrcPortStartMatchCondition 3389 -IPSrcPortEndMatchCondition 3389 -ThrottleRateActionBitsPerSecond 30MB -NetworkProfile All -PolicyStore ActiveStore

    - name: Display RDP Information
      run: |
        $ip = (Test-Connection -ComputerName (hostname) -Count 1).IPV4Address.IPAddressToString
        Write-Output "RDP Connection Information:"
        Write-Output "IP Address: $ip"
        Write-Output "Username: $env:USERNAME"
        Write-Output "Password: [the password you entered]"
        Write-Output "Specifications:"
        Write-Output "- CPU: AMD Ryzen 9 7900X (12 cores)"
        Write-Output "- RAM: 32GB DDR5"
        Write-Output "- Storage: 512GB NVMe SSD"
        Write-Output "- Network: 30Mbps throttled"
        Write-Output "- OS: Windows 11 Pro (Gaming Optimized)"
